import { error, fail, redirect } from '@sveltejs/kit';
import type { PageServerLoad, Actions } from './$types';

export const load: PageServerLoad = async ({
	params,
	locals: { supabase, safeGetSession },
	parent
}) => {
	const { session } = await safeGetSession();
	if (!session) {
		throw error(401, 'Not authenticated');
	}

	// Fire the members query before awaiting the parent layout load so the
	// two don't run as a waterfall.
	const membersPromise = supabase
		.from('band_members')
		.select('id, user_id, role, joined_at')
		.eq('band_id', params.id)
		.order('joined_at');

	const [parentData, { data: membersRaw }] = await Promise.all([parent(), membersPromise]);

	const members = membersRaw ?? [];

	// Fetch profiles for all member user IDs
	const userIds = members.map((m) => m.user_id);
	const { data: profiles } = await supabase
		.from('profiles')
		.select('id, display_name, logo_url')
		.in('id', userIds);

	const profileMap = new Map((profiles ?? []).map((p) => [p.id, p]));

	const enrichedMembers = members.map((m) => ({
		...m,
		display_name: profileMap.get(m.user_id)?.display_name ?? null,
		logo_url: profileMap.get(m.user_id)?.logo_url ?? null
	}));

	return {
		members: enrichedMembers,
		isOwner: parentData.isOwner,
		currentUserId: session.user.id
	};
};

export const actions: Actions = {
	createInvite: async ({ params, url, locals: { supabase, safeGetSession } }) => {
		const { session } = await safeGetSession();
		if (!session) {
			return fail(401, { error: 'Not authenticated' });
		}

		// Verify current user is band owner
		const { data: band } = await supabase
			.from('bands')
			.select('id')
			.eq('id', params.id)
			.eq('owner_id', session.user.id)
			.single();

		if (!band) {
			return fail(403, { error: 'Only the band owner can create invites' });
		}

		// Insert invite (token auto-generated by default column)
		const { data: invite, error: inviteError } = await supabase
			.from('band_invites')
			.insert({ band_id: params.id, created_by: session.user.id })
			.select('token')
			.single();

		if (inviteError || !invite) {
			return fail(500, { error: 'Failed to create invite' });
		}

		const inviteUrl = `${url.origin}/bands/invite/${invite.token}`;
		return { inviteUrl };
	},

	removeMember: async ({ params, request, locals: { supabase, safeGetSession } }) => {
		const { session } = await safeGetSession();
		if (!session) {
			return fail(401, { error: 'Not authenticated' });
		}

		// Verify current user is band owner
		const { data: band } = await supabase
			.from('bands')
			.select('id, owner_id')
			.eq('id', params.id)
			.eq('owner_id', session.user.id)
			.single();

		if (!band) {
			return fail(403, { error: 'Only the band owner can remove members' });
		}

		const formData = await request.formData();
		const memberId = formData.get('member_id') as string;

		if (!memberId) {
			return fail(400, { error: 'Member ID is required' });
		}

		// Prevent owner from removing themselves
		const { data: member } = await supabase
			.from('band_members')
			.select('user_id')
			.eq('id', memberId)
			.eq('band_id', params.id)
			.single();

		if (!member) {
			return fail(404, { error: 'Member not found' });
		}

		if (member.user_id === session.user.id) {
			return fail(400, { error: 'Owner cannot remove themselves. Transfer ownership first.' });
		}

		const { error: deleteError } = await supabase
			.from('band_members')
			.delete()
			.eq('id', memberId)
			.eq('band_id', params.id);

		if (deleteError) {
			return fail(500, { error: 'Failed to remove member' });
		}

		return { removed: true };
	},

	transferOwnership: async ({ params, request, locals: { supabase, safeGetSession } }) => {
		const { session } = await safeGetSession();
		if (!session) {
			return fail(401, { error: 'Not authenticated' });
		}

		// Verify current user is band owner
		const { data: band } = await supabase
			.from('bands')
			.select('id, owner_id')
			.eq('id', params.id)
			.eq('owner_id', session.user.id)
			.single();

		if (!band) {
			return fail(403, { error: 'Only the band owner can transfer ownership' });
		}

		const formData = await request.formData();
		const newOwnerId = formData.get('new_owner_id') as string;

		if (!newOwnerId) {
			return fail(400, { error: 'New owner ID is required' });
		}

		// Verify new owner is a member of this band
		const { data: newOwnerMember } = await supabase
			.from('band_members')
			.select('id')
			.eq('band_id', params.id)
			.eq('user_id', newOwnerId)
			.single();

		if (!newOwnerMember) {
			return fail(400, { error: 'New owner must be a member of the band' });
		}

		// Atomic transfer via RPC: bands.owner_id + both member roles change in
		// one transaction (direct updates are blocked by RLS — bands UPDATE
		// WITH CHECK rejects rows the caller no longer owns, and band_members
		// has no UPDATE policy).
		const { error: transferError } = await supabase.rpc('transfer_band_ownership', {
			p_band_id: params.id,
			p_new_owner_id: newOwnerId
		});

		if (transferError) {
			return fail(500, { error: 'Failed to transfer ownership' });
		}

		return { transferred: true };
	},

	leaveBand: async ({ params, locals: { supabase, safeGetSession } }) => {
		const { session } = await safeGetSession();
		if (!session) {
			return fail(401, { error: 'Not authenticated' });
		}

		// Verify current user is NOT the owner
		const { data: band } = await supabase
			.from('bands')
			.select('owner_id')
			.eq('id', params.id)
			.single();

		if (band?.owner_id === session.user.id) {
			return fail(400, { error: 'Owner cannot leave the band. Transfer ownership first.' });
		}

		// .select() so an RLS-filtered no-op (0 rows) is reported as a failure
		// instead of silently pretending the user left.
		const { data: deletedRows, error: deleteError } = await supabase
			.from('band_members')
			.delete()
			.eq('band_id', params.id)
			.eq('user_id', session.user.id)
			.select('id');

		if (deleteError || !deletedRows?.length) {
			return fail(500, { error: 'Failed to leave band' });
		}

		throw redirect(303, '/bands');
	}
};
