import { error, fail, redirect } from '@sveltejs/kit';
import type { PageServerLoad, Actions } from './$types';

export const load: PageServerLoad = async ({ params, locals: { supabase, safeGetSession }, parent }) => {
	const { session } = await safeGetSession();
	if (!session) {
		throw error(401, 'Not authenticated');
	}

	// Get parent layout data for isOwner
	const parentData = await parent();

	// Load band members with profile info
	const { data: membersRaw } = await supabase
		.from('band_members')
		.select('id, user_id, role, joined_at')
		.eq('band_id', params.id)
		.order('joined_at');

	const members = membersRaw ?? [];

	// Fetch profiles for all member user IDs
	const userIds = members.map((m) => m.user_id);
	const { data: profiles } = await supabase
		.from('profiles')
		.select('id, display_name, logo_url')
		.in('id', userIds);

	const profileMap = new Map((profiles ?? []).map((p) => [p.id, p]));

	const enrichedMembers = members.map((m) => ({
		...m,
		display_name: profileMap.get(m.user_id)?.display_name ?? null,
		logo_url: profileMap.get(m.user_id)?.logo_url ?? null
	}));

	return {
		members: enrichedMembers,
		isOwner: parentData.isOwner,
		currentUserId: session.user.id
	};
};

export const actions: Actions = {
	createInvite: async ({ params, url, locals: { supabase, safeGetSession } }) => {
		const { session } = await safeGetSession();
		if (!session) {
			return fail(401, { error: 'Not authenticated' });
		}

		// Verify current user is band owner
		const { data: band } = await supabase
			.from('bands')
			.select('id')
			.eq('id', params.id)
			.eq('owner_id', session.user.id)
			.single();

		if (!band) {
			return fail(403, { error: 'Only the band owner can create invites' });
		}

		// Insert invite (token auto-generated by default column)
		const { data: invite, error: inviteError } = await supabase
			.from('band_invites')
			.insert({ band_id: params.id, created_by: session.user.id })
			.select('token')
			.single();

		if (inviteError || !invite) {
			return fail(500, { error: 'Failed to create invite' });
		}

		const inviteUrl = `${url.origin}/bands/invite/${invite.token}`;
		return { inviteUrl };
	},

	removeMember: async ({ params, request, locals: { supabase, safeGetSession } }) => {
		const { session } = await safeGetSession();
		if (!session) {
			return fail(401, { error: 'Not authenticated' });
		}

		// Verify current user is band owner
		const { data: band } = await supabase
			.from('bands')
			.select('id, owner_id')
			.eq('id', params.id)
			.eq('owner_id', session.user.id)
			.single();

		if (!band) {
			return fail(403, { error: 'Only the band owner can remove members' });
		}

		const formData = await request.formData();
		const memberId = formData.get('member_id') as string;

		if (!memberId) {
			return fail(400, { error: 'Member ID is required' });
		}

		// Prevent owner from removing themselves
		const { data: member } = await supabase
			.from('band_members')
			.select('user_id')
			.eq('id', memberId)
			.eq('band_id', params.id)
			.single();

		if (!member) {
			return fail(404, { error: 'Member not found' });
		}

		if (member.user_id === session.user.id) {
			return fail(400, { error: 'Owner cannot remove themselves. Transfer ownership first.' });
		}

		const { error: deleteError } = await supabase
			.from('band_members')
			.delete()
			.eq('id', memberId)
			.eq('band_id', params.id);

		if (deleteError) {
			return fail(500, { error: 'Failed to remove member' });
		}

		return { removed: true };
	},

	transferOwnership: async ({ params, request, locals: { supabase, safeGetSession } }) => {
		const { session } = await safeGetSession();
		if (!session) {
			return fail(401, { error: 'Not authenticated' });
		}

		// Verify current user is band owner
		const { data: band } = await supabase
			.from('bands')
			.select('id, owner_id')
			.eq('id', params.id)
			.eq('owner_id', session.user.id)
			.single();

		if (!band) {
			return fail(403, { error: 'Only the band owner can transfer ownership' });
		}

		const formData = await request.formData();
		const newOwnerId = formData.get('new_owner_id') as string;

		if (!newOwnerId) {
			return fail(400, { error: 'New owner ID is required' });
		}

		// Verify new owner is a member of this band
		const { data: newOwnerMember } = await supabase
			.from('band_members')
			.select('id')
			.eq('band_id', params.id)
			.eq('user_id', newOwnerId)
			.single();

		if (!newOwnerMember) {
			return fail(400, { error: 'New owner must be a member of the band' });
		}

		// Update band owner
		await supabase
			.from('bands')
			.update({ owner_id: newOwnerId })
			.eq('id', params.id)
			.eq('owner_id', session.user.id);

		// Update roles: new owner gets 'owner', current user gets 'member'
		await supabase
			.from('band_members')
			.update({ role: 'owner' })
			.eq('band_id', params.id)
			.eq('user_id', newOwnerId);

		await supabase
			.from('band_members')
			.update({ role: 'member' })
			.eq('band_id', params.id)
			.eq('user_id', session.user.id);

		return { transferred: true };
	},

	leaveBand: async ({ params, locals: { supabase, safeGetSession } }) => {
		const { session } = await safeGetSession();
		if (!session) {
			return fail(401, { error: 'Not authenticated' });
		}

		// Verify current user is NOT the owner
		const { data: band } = await supabase
			.from('bands')
			.select('owner_id')
			.eq('id', params.id)
			.single();

		if (band?.owner_id === session.user.id) {
			return fail(400, { error: 'Owner cannot leave the band. Transfer ownership first.' });
		}

		const { error: deleteError } = await supabase
			.from('band_members')
			.delete()
			.eq('band_id', params.id)
			.eq('user_id', session.user.id);

		if (deleteError) {
			return fail(500, { error: 'Failed to leave band' });
		}

		throw redirect(303, '/bands');
	}
};
